use trytes::TRITS_PER_TRYTE;
use ::inner::*;
use super::inner::NONCE_LEN_TRITS;

pub const TRANSACTION_LEN_TRITS: usize = 2673 * TRITS_PER_TRYTE; // = 8019

pub const MESSAGE_TRITS: usize = 6561;
pub const EXTRA_DATA_DIGEST_TRITS: usize = 243;
pub const ADDRESS_TRITS: usize = HASH_LEN_TRITS;
pub const VALUE_TRITS: usize = 81;
pub const ISSUED_AT_TRITS: usize = 27;
pub const ISSUED_AT_LB_TRITS: usize = 27;
pub const ISSUED_AT_UB_TRITS: usize = 27;
pub const BUNDLE_NONCE_TRITS: usize = NONCE_LEN_TRITS;
pub const TRUNK_TRITS: usize = HASH_LEN_TRITS;
pub const BRANCH_TRITS: usize = HASH_LEN_TRITS;
pub const TAG_TRITS: usize = TAG_LEN_TRITS;
pub const ATTACHED_AT_TRITS: usize = 27;
pub const ATTACHED_AT_LB_TRITS: usize = 27;
pub const ATTACHED_AT_UB_TRITS: usize = 27;

pub const EXTRA_DATA_OFFSET: usize = MESSAGE_TRITS;
pub const ADDRESS_OFFSET: usize = EXTRA_DATA_OFFSET + EXTRA_DATA_DIGEST_TRITS;
pub const VALUE_OFFSET: usize = ADDRESS_OFFSET + ADDRESS_TRITS;
pub const ISSUED_AT_OFFSET: usize = VALUE_OFFSET + VALUE_TRITS;
pub const ISSUED_AT_LB_OFFSET: usize = ISSUED_AT_OFFSET + ISSUED_AT_TRITS;
pub const ISSUED_AT_UB_OFFSET: usize = ISSUED_AT_LB_OFFSET + ISSUED_AT_LB_TRITS;
pub const BUNDLE_NONCE_OFFSET: usize = ISSUED_AT_UB_OFFSET + ISSUED_AT_UB_TRITS;
pub const TRUNK_OFFSET: usize = BUNDLE_NONCE_OFFSET + BUNDLE_NONCE_TRITS;
pub const BRANCH_OFFSET: usize = TRUNK_OFFSET + TRUNK_TRITS;
pub const TAG_OFFSET: usize = BRANCH_OFFSET + BRANCH_TRITS;
pub const ATTACHED_AT_OFFSET: usize = TAG_OFFSET + TAG_TRITS;
pub const ATTACHED_AT_LB_OFFSET: usize = ATTACHED_AT_OFFSET + ATTACHED_AT_TRITS;
pub const ATTACHED_AT_UB_OFFSET: usize = ATTACHED_AT_LB_OFFSET + ATTACHED_AT_LB_TRITS;
pub const NONCE_OFFSET: usize = ATTACHED_AT_UB_OFFSET + ATTACHED_AT_UB_TRITS;
