use trytes::{TRITS_PER_TRYTE};
use HASH_LEN_TRITS;

pub const TRANSACTION_LEN_TRITS: usize = 2673 * TRITS_PER_TRYTE;

pub const MESSAGE_TRITS: usize = 6561;
pub const TIMESTAMP_TRITS: usize = 27;
pub const CURRENT_INDEX_TRITS: usize = 27;
pub const LAST_INDEX_TRITS: usize = 27;
pub const VALUE_TRITS: usize = 81;
pub const TAG_TRITS: usize = 81;

pub const ADDRESS_OFFSET: usize = MESSAGE_TRITS;
pub const VALUE_OFFSET: usize = ADDRESS_OFFSET + HASH_LEN_TRITS;
pub const TAG_OFFSET: usize = VALUE_OFFSET + VALUE_TRITS;
pub const TIMESTAMP_OFFSET: usize = TAG_OFFSET + TAG_TRITS;
pub const CURRENT_INDEX_OFFSET: usize = TIMESTAMP_OFFSET + TIMESTAMP_TRITS;
pub const LAST_INDEX_OFFSET: usize = CURRENT_INDEX_OFFSET + CURRENT_INDEX_TRITS;
pub const BUNDLE_OFFSET: usize = LAST_INDEX_OFFSET + LAST_INDEX_TRITS;
pub const TRUNK_OFFSET: usize = BUNDLE_OFFSET + HASH_LEN_TRITS;
pub const BRANCH_OFFSET: usize = TRUNK_OFFSET + HASH_LEN_TRITS;
pub const NONCE_OFFSET: usize = BRANCH_OFFSET + HASH_LEN_TRITS;

pub const ESSENCE_OFFSET: usize = ADDRESS_OFFSET;
pub const ESSENCE_TRITS: usize = HASH_LEN_TRITS + VALUE_TRITS + TAG_TRITS + TIMESTAMP_TRITS + CURRENT_INDEX_TRITS + LAST_INDEX_TRITS;

